### ISSUE TITLE
ValueError using the latest numpy (1.21.5)

### ISSUE THREAD

**Issue by amy12xx** [Farama-Foundation/Miniworld#53]
Similar to #51 I get an error on the following envs when using the latest numpy (1.21.5).  Works fine on version 1.20.
TMazeLeft, TMazeRight, YMazeLeft, YMazeRight

Code snippet to reproduce:
```
import gym
import gym_miniworld

env = gym.make("MiniWorld-TMazeRight-v0")
env.reset()
```

Error:
```
Falling back to num_samples=1
Falling back to num_samples=1
Traceback (most recent call last):
  File "test_world.py", line 4, in <module>
    env = gym.make("MiniWorld-TMazeRight-v0")
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 520, in make
    return spec.make(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 140, in make
    env = cls(**_kwargs)
  File "/content/gym-miniworld/gym_miniworld/envs/tmaze.py", line 79, in __init__
    super().__init__(goal_pos=[10, 0, 6])
  File "/content/gym-miniworld/gym_miniworld/envs/tmaze.py", line 21, in __init__
    **kwargs
  File "/content/gym-miniworld/gym_miniworld/miniworld.py", line 523, in __init__
    self.reset()
  File "/content/gym-miniworld/gym_miniworld/miniworld.py", line 555, in reset
    self._gen_world()
  File "/content/gym-miniworld/gym_miniworld/envs/tmaze.py", line 48, in _gen_world
    max_z=self.goal_pos[2],
  File "/content/gym-miniworld/gym_miniworld/miniworld.py", line 887, in place_entity
    high=[hx - ent.radius, 0, hz - ent.radius]
  File "/content/gym-miniworld/gym_miniworld/random.py", line 24, in float
    return self.np_random.uniform(low, high, size=shape)
  File "_generator.pyx", line 958, in numpy.random._generator.Generator.uniform
  File "_common.pyx", line 562, in numpy.random._common.cont
  File "_common.pyx", line 467, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 350, in numpy.random._common.check_array_constraint
ValueError: high - low < 0
```

It may have to do with how gym's random seeding is implemented. I find that numpy itself does not throw errors for the values passed (for e.g. np.random.uniform(low=[4,7], high=[3,6]) works).

**Comment by maximecb** [comment]
I'm not able to reproduce this bug with the script you provided. Tested on a Linux machine with numpy 1.21.5 and also the latest 1.22.3. If you upgrade do numpy 1.22.3, does that fix the problem?

**Comment by amy12xx** [comment]
Colab's latest version unfortunately appears to be 1.21.5, so I can't test it on 1.22.3. 

However, I tried it again, along with the latest gym version 0.23, and it threw the error. When I downgraded gym to 0.20, it worked fine. Gym seeding could possibly be causing the issue.

**Comment by amy12xx** [comment]
![image](https://user-images.githubusercontent.com/6790637/157804482-8b18b605-c38f-4043-b493-10b24355d576.png)

**Comment by maximecb** [comment]
Might need you to investigate because I can't reproduce it on my end.

**Comment by amy12xx** [comment]
So, this is the offending line, https://github.com/maximecb/gym-miniworld/blob/5f821956eaf8931ec873b6a44d53e7a833e68c87/gym_miniworld/miniworld.py#L885 

```
           pos = self.rand.float(
                low =[lx + ent.radius, 0, lz + ent.radius],
                high=[hx - ent.radius, 0, hz - ent.radius]
            )
```
In case of TMazeRight (and other similar envs), the min_x, and max_x are set to the same values, and min_z and max_z set to the same values.
In which case, the low and high gives values as these:
low = [10.565685424949239, 0, 6.565685424949238]
high = [9.434314575050761, 0, 5.434314575050762]

which the np_random function does not allow anymore. If you instead use low =[lx - ent.radius, 0, lz - ent.radius] and high = [hx + ent.radius, 0, hz + ent.radius], this error goes away. I don't know enough of internal workings of the environment to suggest if this is a good fix or not.

Gym version: 0.23.1
Numpy version: 1.21.5

**Comment by pseudo-rnd-thoughts** [comment]
@amy12xx I have used your proposed solution. But the commit, isn't clear what the correct solution is https://github.com/Farama-Foundation/gym-miniworld/commit/de2e131209bbe1fcd1ac61df1ea2737b63f2f469
