### ISSUE TITLE
[Bug Report] AssertionError: failed to load textures for name "brick_wall"

### ISSUE THREAD

**Issue by GabrielZH** [Farama-Foundation/Miniworld#82]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
I am testing the code of https://github.com/shuishida/calvin, where they tried to experiment their robot control algorithm in the Mini-World Maze environment. When the code was trying to generate the Maze environment, more specifically, to generate the brick-wall texture, here came the AssertionError from opengl.py as it shows below in the Code example.

**Code example**
You can find the upstream call of the class Maze at https://github.com/shuishida/calvin/blob/master/core/domains/miniworld/gym_envs/maze.py

The traceback is like:

Traceback (most recent call last):
  File "core/domains/miniworld/dataset.py", line 51, in <module>
    main()
  File "core/domains/miniworld/dataset.py", line 47, in main
    generate_miniworld_expert_demos(vars(config))
  File "core/domains/miniworld/dataset.py", line 22, in generate_miniworld_expert_demos
    generate_expert_demos(get_save_path, **config)
  File "./core/dataset.py", line 21, in generate_expert_demos
    env = factory.env(meta, data=data, split="train", **env_config)
  File "./core/domains/miniworld/factory.py", line 16, in init_miniworld_env
    env = MiniMaze(num_rows=size, num_cols=size, max_steps=max_steps)
  File "./core/domains/miniworld/gym_envs/maze.py", line 19, in __init__
    domain_rand=False
  File "/data/zhanggengyu/anaconda3/envs/calvin/lib/python3.7/site-packages/miniworld/envs/maze.py", line 28, in __init__
    **kwargs
  File "/data/zhanggengyu/anaconda3/envs/calvin/lib/python3.7/site-packages/miniworld/miniworld.py", line 523, in __init__
    self.reset()
  File "/data/zhanggengyu/anaconda3/envs/calvin/lib/python3.7/site-packages/miniworld/miniworld.py", line 555, in reset
    self._gen_world()
  File "/data/zhanggengyu/anaconda3/envs/calvin/lib/python3.7/site-packages/miniworld/envs/maze.py", line 102, in _gen_world
    self.box = self.place_entity(Box(color='red'))
  File "/data/zhanggengyu/anaconda3/envs/calvin/lib/python3.7/site-packages/miniworld/miniworld.py", line 866, in place_entity
    self._gen_static_data()
  File "/data/zhanggengyu/anaconda3/envs/calvin/lib/python3.7/site-packages/miniworld/miniworld.py", line 990, in _gen_static_data
    self.rand if self.domain_rand else None
  File "/data/zhanggengyu/anaconda3/envs/calvin/lib/python3.7/site-packages/miniworld/miniworld.py", line 243, in _gen_static_data
    self.wall_tex = Texture.get(self.wall_tex_name, rng)
  File "/data/zhanggengyu/anaconda3/envs/calvin/lib/python3.7/site-packages/miniworld/opengl.py", line 57, in get
    assert len(paths) > 0, 'failed to load textures for name "%s"' % tex_name
AssertionError: failed to load textures for name "brick_wall"

**System Info**
Describe the characteristic of your environment:
 * Describe how `gym-miniworld` was installed: using your recommended way of installing, python3 -m pip install miniworld
 * What OS/version of Linux you're using: Ubuntu 20.04
 * Python version: Python 3.7

**Additional context**

### Checklist

- [✓] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/gym-miniworld/issues) in the repo (**required**)

**Comment by GabrielZH** [comment]
I figured out the culprit of the issue, which is that the installed package did not contain the textures/ and meshes/ directories. I manually downloaded them and placed them under the miniworld/ directory. This issue seems to be resolved.

However, I then got another error:

Traceback (most recent call last):
  File "/data/zhanggengyu/projects/baselines/calvin/core/domains/miniworld/dataset.py", line 51, in <module>
    main()
  File "/data/zhanggengyu/projects/baselines/calvin/core/domains/miniworld/dataset.py", line 47, in main
    generate_miniworld_expert_demos(vars(config))
  File "/data/zhanggengyu/projects/baselines/calvin/core/domains/miniworld/dataset.py", line 22, in generate_miniworld_expert_demos
    generate_expert_demos(get_save_path, **config)
  File "/data/zhanggengyu/projects/baselines/calvin/./core/dataset.py", line 21, in generate_expert_demos
    env = factory.env(meta, data=data, split="train", **env_config)
  File "/data/zhanggengyu/projects/baselines/calvin/./core/domains/miniworld/factory.py", line 16, in init_miniworld_env
    env = MiniMaze(num_rows=size, num_cols=size, max_steps=max_steps)
  File "/data/zhanggengyu/projects/baselines/calvin/./core/domains/miniworld/gym_envs/maze.py", line 14, in __init__
    super().__init__(
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/miniworld/envs/maze.py", line 26, in __init__
    super().__init__(
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/miniworld/miniworld.py", line 523, in __init__
    self.reset()
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/miniworld/miniworld.py", line 555, in reset
    self._gen_world()
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/miniworld/envs/maze.py", line 102, in _gen_world
    self.box = self.place_entity(Box(color='red'))
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/miniworld/miniworld.py", line 866, in place_entity
    self._gen_static_data()
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/miniworld/miniworld.py", line 988, in _gen_static_data
    room._gen_static_data(
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/miniworld/miniworld.py", line 243, in _gen_static_data
    self.wall_tex = Texture.get(self.wall_tex_name, rng)
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/miniworld/opengl.py", line 67, in get
    self.tex_cache[path] = Texture(Texture.load(path), tex_name)
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/miniworld/opengl.py", line 82, in load
    glEnable(tex.target)
  File "/home/zhanggengyu/.local/lib/python3.7/site-packages/pyglet/gl/lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x500): Invalid enum. An unacceptable value is specified for an enumerated argument.

Not sure what is the cause this time...

**Comment by BolunDai0216** [comment]
Can you check your `pyglet` version?

**Comment by BolunDai0216** [comment]
Can you downgrade it to 1.5.27 and see if that solves the problem?

**Comment by GabrielZH** [comment]
I found that installing gym_miniworld (using pip as provided in https://pypi.org/project/gym-miniworld/, might be a previous version?) instead of the current miniworld solves the issue. Do I still need to test pyglet 1.5.27 on the current version of miniworld or it's safe to close the issue?

**Comment by BolunDai0216** [comment]
You can close the issue.

**Comment by raymondchua** [comment]
2.0.9 does not work. I had to install 1.5.27 to get it working.
